name: Deploy Serverless SSR (Dev)

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Get yarn cache
      id: yarn-cache
      run: echo "::set-output name=dir::$(yarn cache dir)"

    - uses: actions/cache@v1
      with:
        path: ${{ steps.yarn-cache.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - name: yarn install
      uses: borales/actions-yarn@v2.0.0
      with:
        cmd: install
    - name: npm run build:ci
      run: npm run build:ci
      env:
        REACT_APP_API_HOST: 'https://v2dev.velog.io/'
        PUBLIC_URL: 'https://d3v0gm8v6v8olv.cloudfront.net/'
        STAGE: true
    - name: s3 sync
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET_DEV }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
        AWS_REGION: 'ap-northeast-2'
        SOURCE_DIR: 'build'

    - name: serverless deploy
      uses: serverless/github-action@master
      with:
        args: deploy --stage production
      env:
        # or if using AWS creds directly
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
        REACT_APP_API_HOST: 'https://v2dev.velog.io/'
        PUBLIC_URL: 'https://d3v0gm8v6v8olv.cloudfront.net/'
        STAGE: true
    - name: Deploy Completion Webhook
      uses: joelwmale/webhook-action@master
      env:
        WEBHOOK_URL: ${{ secrets.SSR_COMPLETE_WEBHOOK }}
        data: "{'deployment': 'finished'}"
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2.0.0
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_USERNAME: 'Github Actions'
        SLACK_ICON: 'https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png'
        SLACK_MESSAGE: '*stage: dev* - 벨로그 웹 클라이언트 배포가 끝났어요! :rocket:'